POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHJlbmtlaHVhbmcubmV0IiwiZXhwIjoxNzQ1MjE1MjU0LCJ1c2VySWQiOjF9.eEjr3K0KNe_BqpwHDbV0UcQzXZPNeIQhW53OSLVFdR0

{
  "name": "Test Event",
  "description": "This is the test event",
  "location": "Test Location",
  "dateTime": "2025-04-20T10:00:00Z"
}