POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHJlbmtlaHVhbmcubmV0IiwiZXhwIjoxNzQ1MjU5MjQyLCJ1c2VySWQiOjF9.qNhT9q2zaapf1LXmlvkcEggtlIJcUam717rxZibPvR0

{
  "name": "Test Event",
  "description": "This is the test event",
  "location": "Test Location",
  "dateTime": "2025-04-20T10:00:00Z"
}