DELETE http://localhost:8080/events/1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQHJlbmtlaHVhbmcubmV0IiwiZXhwIjoxNzQ1MjE1MzU4LCJ1c2VySWQiOjJ9.Sw9cJrfqOUf4O82yTKwxmiGFXBaOL7lnBkzOWoQSUU0
