PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQHJlbmtlaHVhbmcubmV0IiwiZXhwIjoxNzQ1MjE1MzU4LCJ1c2VySWQiOjJ9.Sw9cJrfqOUf4O82yTKwxmiGFXBaOL7lnBkzOWoQSUU0

{
  "name": "Updated Event",
  "description": "This is an updated test event",
  "location": "Updated Location",
  "dateTime": "2023-10-02T10:00:00Z"
}